version: '3.7'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:${VERSION}
    restart: unless-stopped
    environment:
      - TZ=${TIME_ZONE}
      - PLEX_CLAIM=${CLAIM_CODE}
    network_mode: host
    volumes:
      - type: bind
        target: /config
        source: ${ROOT_DIR}/config
      - type: bind
        target: /data
        source: ${DATA_DIR}/media/original
      - type: bind
        target: /transcode
        source: ${DATA_DIR}/media/transcode
