version: '3.7'

services:
  openhab:
    image: "openhab/openhab:${VERSION}"
    container_name: openhab_server
    restart: always
    network_mode: host
    volumes:
      - type: bind
        target: /openhab/addons
        source: ${ROOT_DIR}/addons
      - type: bind
        target: /openhab/conf
        source: ${ROOT_DIR}/config
      - type: bind
        target: /openhab/userdata
        source: ${ROOT_DIR}/data
    environment:
      OPENHAB_HTTP_PORT: "2020"
      OPENHAB_HTTPS_PORT: "2443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=${TIME_ZONE}"
