version: '3.7'

services:
  dyndns:
    image: mmprivat/selfhost-updater:${VERSION} 
    container_name: selfhost-updater
    restart: always
    volumes:
      - type: volume
        target: /etc/selfhost
        source: data
    environment:
      USERID: ${USERNAME}
      PASSWORD: ${PASSWORD}
      URL: remote.selfhost.de 
    networks:
      - backend

volumes:
  data:
    name: selfhost-updater_data

networks:
  backend:
    name: selfhost-updater
